### ISSUE TITLE
Create a plugin structure

### ISSUE THREAD

**Issue by zac23or** [EvandroLG/pegasus.lua#32]
Proposal: extends pegasus with a plugin

require 'pegasus.lua'
require 'upload.lua'

**Comment by o-jasper** [comment]
Instead of having it at the top could it be done in a way that you call functions that then go through the plugin lists.

    function(request, response)
        if request.path == "/a" then
            deal_with_it_list(plugin_list_a)(request, response)
        elseif request.path == "/b" then
            deal_with_it_list(plugin_list_b)(request, response)
        end
    end

Or, why lists, could have table correspond to the paths..

    function deal_with_it_tree(using, at_path)
       return function (request, response)
           local tp = type(using)
           if tp == "function" then
              return using(request, response)
           elseif tp == "table" then   -- Metatables would still work too.
              -- Note that if you need multiple methods, you'd need to have an indicator element.
              local _, j = string.find(at_path, "/", true)
              return deal_with_it_tree(using[string.sub(at_path, 1, j)],
                                   string.sub(at_path, j))(request, response)
           elseif using == "file" then
              return via_file(request, response)
           end       
        end
    end

The above might be: `deal_with_it_tree({ a= deal_with_it_list(plugin_list_a), b= deal_with_it_list(plugin_list_b) })` basically, responses are constructed from functions. Could in principle construct them from objects of course, instead of calling the functions, you just call a method of the object. That'd make it easier to access as-data.

Might it be possible to do `compress.lua` and `cache.lua` "afterward"? `cache(compress(responder))`, not clear to me if that is possible.

**Comment by zac23or** [comment]
Hello @o-jasper! Some points:

1. The plugin idea is stop the request process (block by ip) or process input/output (gzip, etc).
2 . the idea of request:path is call a function that can be a plugin.

3. Plugin code stay in developer branch. Developer branch is not a stable branch. In the end, cache and compress will stay in another repository.

**Comment by o-jasper** [comment]
How solid is the state of the plugins now? Mightbe nice to have a little doc describing what you can/must provide to have an object be a plugin?

**Comment by EvandroLG** [comment]
@o-jasper our intention is provide documentation about creation of plugins in the next release - in the next weeks :)
I guess this structure is good. I'd like to add more tests about it before disclosing the documentation
